from decimal import Decimal

SAMPLE_CATEGORIES = [
    {'id': 1, 'name': 'Coffee', 'slug': 'coffee', 'display_order': 1},
    {'id': 2, 'name': 'Meals', 'slug': 'meals', 'display_order': 2},
    {'id': 3, 'name': 'Snacks', 'slug': 'snacks', 'display_order': 3},
    {'id': 4, 'name': 'Dessert', 'slug': 'dessert', 'display_order': 4},
    {'id': 5, 'name': 'Cold Drinks', 'slug': 'cold-drinks', 'display_order': 5},
    {'id': 6, 'name': 'Fast Food', 'slug': 'fast-food', 'display_order': 6},
]

SAMPLE_TABLES = [{'id': index, 'name': f'T{index}', 'seats': 4, 'status': 'available'} for index in range(1, 7)]

SAMPLE_PRODUCTS = [
    {
        'id': 1,
        'name': 'Cappuccino',
        'price': 180.0,
        'category': 'coffee',
        'category_name': 'Coffee',
        'stock_status': 'in_stock',
        'quantity': 30,
        'description': 'Velvety espresso with steamed milk and foam.',
        'image_url': 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 2,
        'name': 'Espresso',
        'price': 120.0,
        'category': 'coffee',
        'category_name': 'Coffee',
        'stock_status': 'in_stock',
        'quantity': 40,
        'description': 'Short, rich, and aromatic cafe classic.',
        'image_url': 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 3,
        'name': 'Latte',
        'price': 140.0,
        'category': 'coffee',
        'category_name': 'Coffee',
        'stock_status': 'in_stock',
        'quantity': 25,
        'description': 'Rich espresso with steamed milk and a thin layer of foam.',
        'image_url': 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 4,
        'name': 'Mocha',
        'price': 160.0,
        'category': 'coffee',
        'category_name': 'Coffee',
        'stock_status': 'in_stock',
        'quantity': 15,
        'description': 'Espresso combined with chocolate syrup and steamed milk.',
        'image_url': 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 5,
        'name': 'Americano',
        'price': 110.0,
        'category': 'coffee',
        'category_name': 'Coffee',
        'stock_status': 'in_stock',
        'quantity': 40,
        'description': 'Rich espresso shot diluted with hot water.',
        'image_url': 'https://images.unsplash.com/photo-1551030173-122aabc4489c?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 6,
        'name': 'Cold Coffee',
        'price': 150.0,
        'category': 'coffee',
        'category_name': 'Coffee',
        'stock_status': 'in_stock',
        'quantity': 20,
        'description': 'Chilled milk, espresso, and ice cream blended perfectly.',
        'image_url': 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 7,
        'name': 'Hazelnut Cappuccino',
        'price': 190.0,
        'category': 'coffee',
        'category_name': 'Coffee',
        'stock_status': 'in_stock',
        'quantity': 12,
        'description': 'Classic cappuccino infused with warm hazelnut syrup.',
        'image_url': 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 8,
        'name': 'White Sauce Pasta',
        'price': 240.0,
        'category': 'meals',
        'category_name': 'Meals',
        'stock_status': 'in_stock',
        'quantity': 15,
        'description': 'Penne pasta tossed in rich, creamy bechamel sauce with vegetables.',
        'image_url': 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 9,
        'name': 'Alfredo Pasta',
        'price': 260.0,
        'category': 'meals',
        'category_name': 'Meals',
        'stock_status': 'out_of_stock',
        'quantity': 0,
        'description': 'Creamy fettuccine Alfredo tossed with parmesan and fresh herbs.',
        'image_url': 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 10,
        'name': 'Paneer Wrap',
        'price': 180.0,
        'category': 'meals',
        'category_name': 'Meals',
        'stock_status': 'low_stock',
        'quantity': 5,
        'description': 'Grilled tortilla wrapped with spiced paneer, veggies, and mint mayo.',
        'image_url': 'https://images.unsplash.com/photo-1626700051175-6518c4793fde?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 11,
        'name': 'Garlic Bread',
        'price': 120.0,
        'category': 'snacks',
        'category_name': 'Snacks',
        'stock_status': 'in_stock',
        'quantity': 25,
        'description': 'Toasted artisan bread topped with garlic butter and fresh parsley.',
        'image_url': 'https://images.unsplash.com/photo-1573140247632-f8fd74997d5c?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 12,
        'name': 'Nachos',
        'price': 160.0,
        'category': 'snacks',
        'category_name': 'Snacks',
        'stock_status': 'in_stock',
        'quantity': 14,
        'description': 'Crispy corn tortilla chips served with bubbling cheese sauce and salsa.',
        'image_url': 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 13,
        'name': 'French Fries',
        'price': 100.0,
        'category': 'snacks',
        'category_name': 'Snacks',
        'stock_status': 'in_stock',
        'quantity': 35,
        'description': 'Crispy golden classic potato fries sprinkled with sea salt.',
        'image_url': 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 14,
        'name': 'Club Sandwich',
        'price': 180.0,
        'category': 'snacks',
        'category_name': 'Snacks',
        'stock_status': 'in_stock',
        'quantity': 12,
        'description': 'Triple-decker sandwich with layered vegetables, cheese, and herb spread.',
        'image_url': 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 15,
        'name': 'Peri Peri Fries',
        'price': 130.0,
        'category': 'snacks',
        'category_name': 'Snacks',
        'stock_status': 'low_stock',
        'quantity': 4,
        'description': 'Crispy french fries tossed in spicy peri peri seasoning.',
        'image_url': 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 16,
        'name': 'Choco Lava Cake',
        'price': 150.0,
        'category': 'dessert',
        'category_name': 'Dessert',
        'stock_status': 'in_stock',
        'quantity': 18,
        'description': 'Warm chocolate cake filled with rich oozing molten chocolate lava.',
        'image_url': 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 17,
        'name': 'Red Velvet Pastry',
        'price': 140.0,
        'category': 'dessert',
        'category_name': 'Dessert',
        'stock_status': 'in_stock',
        'quantity': 10,
        'description': 'Layers of moist red velvet cake filled with creamy cream cheese frosting.',
        'image_url': 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 18,
        'name': 'Brownie Sundae',
        'price': 180.0,
        'category': 'dessert',
        'category_name': 'Dessert',
        'stock_status': 'in_stock',
        'quantity': 15,
        'description': 'Hot chocolate brownie topped with vanilla ice cream and hot fudge.',
        'image_url': 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 19,
        'name': 'Glazed Donut',
        'price': 90.0,
        'category': 'dessert',
        'category_name': 'Dessert',
        'stock_status': 'in_stock',
        'quantity': 30,
        'description': 'Classic soft yeast-raised donut coated in sweet sugar glaze.',
        'image_url': 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 20,
        'name': 'Virgin Mojito',
        'price': 130.0,
        'category': 'cold-drinks',
        'category_name': 'Cold Drinks',
        'stock_status': 'in_stock',
        'quantity': 20,
        'description': 'Refreshing blend of lime, fresh mint leaves, sugar, and carbonated soda.',
        'image_url': 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 21,
        'name': 'Oreo Shake',
        'price': 160.0,
        'category': 'cold-drinks',
        'category_name': 'Cold Drinks',
        'stock_status': 'in_stock',
        'quantity': 22,
        'description': 'Thick creamy milkshake blended with vanilla ice cream and Oreo cookies.',
        'image_url': 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 22,
        'name': 'Chocolate Shake',
        'price': 150.0,
        'category': 'cold-drinks',
        'category_name': 'Cold Drinks',
        'stock_status': 'in_stock',
        'quantity': 25,
        'description': 'Decadent milkshake made with premium cocoa and chocolate ice cream.',
        'image_url': 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 23,
        'name': 'Strawberry Smoothie',
        'price': 170.0,
        'category': 'cold-drinks',
        'category_name': 'Cold Drinks',
        'stock_status': 'in_stock',
        'quantity': 15,
        'description': 'Healthy blend of fresh strawberries, yogurt, and honey.',
        'image_url': 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 24,
        'name': 'Cheese Burger',
        'price': 190.0,
        'category': 'fast-food',
        'category_name': 'Fast Food',
        'stock_status': 'in_stock',
        'quantity': 20,
        'description': 'Classic grilled patty topped with melted cheddar, lettuce, and tomatoes.',
        'image_url': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 25,
        'name': 'Paneer Tikka Pizza',
        'price': 320.0,
        'category': 'fast-food',
        'category_name': 'Fast Food',
        'stock_status': 'in_stock',
        'quantity': 15,
        'description': 'Pizza crust loaded with spiced tandoori paneer cubes, capsicum, and onions.',
        'image_url': 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?auto=format&fit=crop&w=600&q=80',
    },
    {
        'id': 26,
        'name': 'Veg Spring Rolls',
        'price': 140.0,
        'category': 'fast-food',
        'category_name': 'Fast Food',
        'stock_status': 'in_stock',
        'quantity': 18,
        'description': 'Crispy golden rolls filled with sauteed mixed vegetables and glass noodles.',
        'image_url': 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    },
]


def calculate_totals(items):
    subtotal = sum(Decimal(str(item['price'])) * int(item['quantity']) for item in items)
    gst = (subtotal * Decimal('0.05')).quantize(Decimal('0.01'))
    total = subtotal + gst
    return subtotal.quantize(Decimal('0.01')), gst, total.quantize(Decimal('0.01'))
