"""rename name to table_name

Revision ID: 6d211f8ce7e9
Revises: c0f5f55f7a3d
Create Date: 2026-06-14 01:55:18.450475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d211f8ce7e9'
down_revision = 'c0f5f55f7a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tables_name_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['table_name'])
        batch_op.drop_column('name')
        batch_op.drop_column('seats')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seats', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('tables_name_key'), ['name'])

    # ### end Alembic commands ###
